### ISSUE TITLE
CS - UI Meters Listen for changes

### ISSUE THREAD

**Issue by JackStillwell** [VincentShaneFinn/WorkshopPart2#35]
Make it so rather than getting set in an update in HealthSystem, UI meters listen for changes in health in their parents

Will require making events when health needs to be updated in Health System and having the UI meter listen for those events. Will also need to make a enemy UI_meter that subscribes to the HealthSystem in its parent, and a player ui meter that subscribes to the Health System in the PlayerUI

**Comment by mart338** [comment]
Resolved in issue #34
